.PHONY = E7-CPU+RAM+DD clean
CC     = g++
CFLAGS = -Wall -Wextra -g -lpthread

E7-CPU+RAM+DD: E7-CPU+RAM+DD.cpp
	$(CC) E7-CPU+RAM+DD.cpp -o E7-CPU+RAM+DD $(CFLAGS)

clean:
	@echo "Cleaning up..."
	rm E7-CPU+RAM+DD pepe
